# Generated by Django 2.2.3 on 2019-07-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_icone', models.ImageField(upload_to='pictures')),
                ('date_debut', models.DateField(auto_now=True)),
                ('date_fin', models.DateField(auto_now=True)),
                ('nom_course', models.CharField(max_length=80)),
                ('ville_course', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipes', models.CharField(max_length=100)),
                ('sous_titre', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('drapeau', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Pilotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pilote', models.TextField()),
                ('numéro', models.IntegerField()),
                ('date_naissance', models.DateField(auto_now=True)),
                ('nationalité', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures')),
                ('drapeau_pilote', models.ImageField(upload_to='pictures')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pilote', to='pariSportif.Equipes')),
            ],
        ),
    ]
