# Generated by Django 2.2.3 on 2019-07-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pariSportif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_equipes', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('Pays', models.CharField(max_length=100)),
                ('Drapeau', models.ImageField(upload_to='pictures')),
                ('Icone', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.AlterField(
            model_name='pilotes',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes_pilote', to='pariSportif.Equipe'),
        ),
        migrations.DeleteModel(
            name='Equipes',
        ),
    ]
